#!/usr/bin/env python3
"""Generate the SaltMon lid panel schematic (LidPanel.kicad_sch).

The lid panel is passive: 8 flat-top 5 mm LEDs, solder pads for the panel-mounted slide switch and push-button,
and J1, a 2×8 shrouded header wired 1:1 to the carrier's J_PANEL (docs/requirements.md §5.2) over a 16-way ribbon
with an IDC socket at each end. The current resistors, the LED driver and the button pull-up stay on the carrier.

Run:  python3 kicad/LidPanel/gen_schematic.py
Check: kicad-cli sch erc kicad/LidPanel/LidPanel.kicad_sch
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "lib"))
from schgen import G, init, note, place, text, write  # noqa: E402

OUT = HERE / "LidPanel.kicad_sch"
init("LidPanel", "7d3e1f52-4b0a-4c3e-9a51-2f6c8e0b1d47", "5a1f0000-5a17-4d0e-8000-00000000a1d0")

FP_LED = "LED_THT:LED_D5.0mm_FlatTop"
FP_WIRE = "Connector_Wire:SolderWire-0.5sqmm_1x02_P4.6mm_D0.9mm_OD2.1mm"

# ---------------------------------------------------------------- 1. ribbon header

note("1. J1  to carrier J_PANEL (req §5.2)", 20.32, 25.4)
text("2x8 shrouded, right-angle, on the back of the board.\n16-way ribbon, IDC socket at each end, 1:1.\n"
     "SW_A/SW_B each use two conductors.", 20.32, 27.94)
JP = {str(i): f"LED_A{i}" for i in range(1, 9)}
JP.update({"9": "LED_PWR", "10": "BTN_N", "11": "SW_A", "12": "SW_A", "13": "SW_B", "14": "SW_B",
           "15": "GND", "16": "GND"})
place("Connector_Generic:Conn_02x08_Odd_Even", "J1", "J_LID", G * 16, G * 30, JP,
      fp="Connector_IDC:IDC-Header_2x08_P2.54mm_Horizontal")

# ---------------------------------------------------------------- 2. LEDs

note("2. LEDs  flat-top 5 mm (req §5.1, §5.4)", 81.28, 25.4)
text("Anodes come from the carrier's current resistors (R1-R9); cathodes to GND.\n"
     "D7: 3-lead common-cathode bi-color, pin 1 red / 2 K / 3 green (check the part).", 81.28, 27.94)
LEDS = [("D1", "Green", "FULL", "LED_A1"), ("D2", "Yellow", "MID", "LED_A2"), ("D3", "Orange", "LOW", "LED_A3"),
        ("D4", "Red", "REFILL", "LED_A4"), ("D5", "Blue", "DATA", "LED_A5"), ("D6", "Purple", "SENS", "LED_A6"),
        ("D8", "White", "PWR", "LED_PWR")]
for i, (ref, color, name, net) in enumerate(LEDS):
    place("Device:LED", ref, color, G * (36 + 8 * i), G * 22, {"1": "GND", "2": net}, rot=90, fp=FP_LED,
          fields={"Description": f"{name}, 5 mm flat-top"})
place("Device:LED_Dual_AKA", "D7", "Red/Green", G * 48, G * 36, {"1": "LED_A8", "2": "GND", "3": "LED_A7"},
      fp="LED_THT:LED_D5.0mm-3", fields={"Description": "NET, 5 mm flat-top bi-color, common cathode"})

# ---------------------------------------------------------------- 3. panel parts, mech

note("3. PANEL SWITCH / BUTTON  (wired to pads)", 20.32, 88.9)
text("SW1 slide switch (power loop) and SW2 push-button are panel-mounted in the lid\n"
     "and wired to J2/J3 with short leads.", 20.32, 91.44)
place("Connector_Generic:Conn_01x02", "J2", "SW1", G * 12, G * 44, {"1": "SW_A", "2": "SW_B"}, fp=FP_WIRE,
      fields={"Description": "Pads for the panel slide switch (common + one throw)"}, bom=False)
place("Connector_Generic:Conn_01x02", "J3", "SW2", G * 24, G * 44, {"1": "BTN_N", "2": "GND"}, fp=FP_WIRE,
      fields={"Description": "Pads for the panel push-button"}, bom=False)
for i in range(4):
    place("Mechanical:MountingHole", f"H{i + 1}", "M3", G * (48 + 6 * i), G * 44, {},
          fp="MountingHole:MountingHole_3.2mm_M3", bom=False)

# ---------------------------------------------------------------- write

write(OUT, "SaltMon lid panel", "2026-09-30", "0.1",
      ["Generated by kicad/LidPanel/gen_schematic.py - edit the script, not this file",
       "Pin map: docs/pinmap.md   Requirements: docs/requirements.md"], paper="A4")
